version: '3'
services:
  db:
    build: ./docker/db
    ports:
      - 5434:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
    # command: bash -c "python manage.py runserver 0.0.0.0:8081"
    tty: true
    depends_on:
      - db

